before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: eAbHm7CBy9rMffzWbiMMLCJsiO77jOmOXH0haCFE3HRoRdqRa7iu7jeiK0eOb7WkDYaHTvdKtvUxXrHWELm6GT6ZqftJOCubub1gNuXpPqlgg4dMsVwPzSFVOzuE0xAMRZgl9r9do3bw6tF9hjc10ISkOmMb/+RvHbQh5Xjot+rcRGp1xJLWzo1LPiCB9uNYiHnP8k6rALv3XI6FvgoZnsyRyP/Yp/jmjG/pWWDaYBGfN8JJHUrTswxW24QvlBb/lRg05Uqp+eW10Cd4Jv7xV8B7qUCTlEuV17s2lRBCcIjbVCZ+M4GwCc+fUerW9hTIPWrAHu9xf9ZgvYL2EDXOowBf3MANVlLHlTMwt14gz/87WdeVVt1yZ2NmSeaLS0OO53Ix13IP0JA+oGEvQeWif0/Brn3Cge1POJDw2sepkQ7C2DX+0w+YsSw4PWFJ3DvCaK3wJxerRsGDKVlOyiohNPGWDtCk6OisAX1BPhjtcNwkKIiwSMHuqcRr3JqfQEveEORCs2cOawcsfvPMeRIU/hM1YPA/byQK0Hi/kwGkhztpo4ZdKMfTbjX3GmPRZ1tAVR9aB+hE38066Hd20JIFfee8Z70XGkZfGlrxVFEzsPhKxxxptVNEWva3MQQyrGMQNhsenJh7toEg4phboCqQgrC8rIFn8Dp9h+lNr1pP5ZQ= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
